version: '3.5'

networks:
  modos_network:
      driver: bridge

services:

  modos_api:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - modos_db
    command: npm start
    networks:
      - modos_network

  modos_db:
    image: postgres
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
    ports:
      - "5432:5432"
    networks:
      - modos_network
